POST https://evening-island-44720.herokuapp.com/api/registrant
Content-Type: application/json

{
    "title": "Bro",
    "firstname": "Jason",
    "othername": "Nii",
    "lastname": "Addy",
    "email": "dama232@gmail.com",
    "dateofbirth": "1979-12-22",
    "phonenumber": "0207410032",
    "position":"Lay",
    "circuit": "Accra",
    "category": "Delegate",
    "circuitorganisation": "YOUTH FELLOWSHIP"
}